# vi: set ft=ruby :
 
Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-17.04"
    config.vm.synced_folder ENV['HOME'], "/myhome", type: "nfs"

    config.vm.provider "vmware_fusion" do |v|
      v.memory = 2048
      v.cpus = 1
    end
 
    config.vm.define "tc-k-wmv-m-master" do |node|
      node.vm.hostname = "tc-k-wmv-m-master"
      node.vm.network "private_network", type: "dhcp"

      # Use NFS for shared folders for better performance
      node.vm.synced_folder '.', '/vagrant', nfs: true
    end 

   config.vm.define "tc-k-wmv-m-worker-01" do |node|
      node.vm.hostname = "tc-k-wmv-m-worker-01"
      node.vm.network "private_network", type: "dhcp"

      # Use NFS for shared folders for better performance
      node.vm.synced_folder '.', '/vagrant', nfs: true
    end 
  config.vm.define "tc-k-wmv-m-worker-02" do |node|
      node.vm.hostname = "tc-k-wmv-m-worker-02"
      node.vm.network "private_network", type: "dhcp"

      # Use NFS for shared folders for better performance
      node.vm.synced_folder '.', '/vagrant', nfs: true
    end 
end
