# vi: set ft=ruby :
 
Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-17.04"
    # config.vm.synced_folder ENV['HOME'], "/myhome", type: "nfs"

    config.vm.provider "vmware_fusion" do |v|
      v.memory = 1024
      v.cpus = 1
      v.gui = true
      v.name = "tc-k-vm-master"
      # Fusion Performance Hacks
      v.vmx["custom-key"]  = "value"
      v.vmx["logging"] = "FALSE"
      v.vmx["custom-key"]  = "value"
      v.vmx["MemTrimRate"] = "0"
      v.vmx["MemAllowAutoScaleDown"] = "FALSE"
      v.vmx["mainMem.backing"] = "swap"
      v.vmx["sched.mem.pshare.enable"] = "FALSE"
      v.vmx["snapshot.disabled"] = "TRUE"
      v.vmx["isolation.tools.unity.disable"] = "TRUE"
      v.vmx["unity.allowCompostingInGuest"] = "FALSE"
      v.vmx["unity.enableLaunchMenu"] = "FALSE"
      v.vmx["unity.showBadges"] = "FALSE"
      v.vmx["unity.showBorders"] = "FALSE"
      v.vmx["unity.wasCapable"] = "FALSE"
      # enable nested hypervisor
      v.vmx["vhv.enable"] = "TRUE"
    end
 
    config.vm.define "tc-k-vm-master" do |node|
      node.vm.hostname = "tc-k-vm-master"
      # node.vm.network "private_network", type: "dhcp"
      node.vm.network :public_network
      node.vm.provision :shell, path: "bootstrap.sh"

      # Use NFS for shared folders for better performance
      # node.vm.synced_folder '.', '/vagrant', nfs: true
    end 
end
